# Generated by Django 5.0.6 on 2024-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customerssays'),
    ]

    operations = [
        migrations.CreateModel(
            name='KryptoExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10000)),
                ('telegram_username', models.CharField(max_length=95)),
                ('credit_card', models.CharField(max_length=80)),
                ('credit_card_placeholder', models.CharField(max_length=80)),
                ('valyuta', models.CharField(max_length=40)),
                ('uzs', models.CharField(max_length=50)),
            ],
        ),
    ]
